### ISSUE TITLE
[Bug]:部署卡主了，需要拉取外网资源？

### ISSUE THREAD

**Issue by zmyer** [linktimecloud/kubernetes-data-platform#193]
### KDP version

1.1.0

### What did you do?

部署卡主了
![image](https://github.com/user-attachments/assets/b9898c0a-6d66-4cfa-9f4c-9b13d0d470f5)

### What did you see happen?

如何解决
![image](https://github.com/user-attachments/assets/0cb44fe0-fab4-45ac-b5b0-4b3a108965d1)

### What did you expect to see?

如何解决
![image](https://github.com/user-attachments/assets/2fc8c654-37fa-4cf4-be70-e8c928c88e0b)

**Comment by harlee-x** [comment]
please use `/root/.kdp/bin/vela status addon-plg-stack -n vela-system` to check the installation status of components under the plg and see which component is abnormal during installation
- You are advised to add the --set dnsService.name=kube-dns parameter during installation，If the loik-gateway dns is incorrectly configured, pod exceptions occur, causing plg installation failure

**Comment by zmyer** [comment]
> please use `/root/.kdp/bin/vela status addon-plg-stack -n vela-system` to check the installation status of components under the plg and see which component is abnormal during installation
> 
> * You are advised to add the --set dnsService.name=kube-dns parameter during installation，If the loik-gateway dns is incorrectly configured, pod exceptions occur, causing plg installation failure

it's not work，vela is not installed successfully，Maybe is network problem，Emmm, but how can I deal with it?

**Comment by zmyer** [comment]
is this problem?
![image](https://github.com/user-attachments/assets/f0ebc775-97d1-4b9f-be54-d9c20f5c69ca)

**Comment by zmyer** [comment]
![image](https://github.com/user-attachments/assets/eb0b23f7-1b92-4707-bea4-4618026a918a)

**Comment by harlee-x** [comment]
please delete prometheusCRD.enabled=false parameter  to retry

**Comment by zmyer** [comment]
> /vela status addon-plg-stack -n vela-system

it's not work,


> please delete prometheusCRD.enabled=false parameter to retry
it's not work
![image](https://github.com/user-attachments/assets/1fff49ec-ee02-41cd-a469-515a1d96f793)

**Comment by harlee-x** [comment]
can you give me install command?

**Comment by zmyer** [comment]
I have dealed with it， Thanks

**Comment by harlee-x** [comment]
The Prometheus CRD installed by KubeSphere is inconsistent with the Prometheus CRD installed by KDP (missing attachMetadata), causing an exception.

1. Refer to the provided link [to](https://www.kubesphere.io/zh/docs/v3.4/faq/observability/byop/) uninstall KubeSphere's Prometheus and install KDP's Prometheus.
2. edit crd `servicemonitors.monitoring.coreos.com`  location at `spec.versions.[0]schema.openAPIV3Schema.properties.spec` add
``` 
spec:
  versions:
   - schema:
        openAPIV3Schema:
          ...
          properties:
            spec:
              attachMetadata:
                description: "`attachMetadata` defines additional metadata which is
                  added to the discovered targets. \n It requires Prometheus >= v2.37.0."
                properties:
                  node:
                    description: When set to true, Prometheus must have the `get`
                      permission on the `Nodes` objects.
                    type: boolean
                type: object
          ...
```
